version: '3.9'

services:

  api: &api
    build: 
      context: .
      dockerfile: Dockerfile
    command: [ "rails s -b 0.0.0.0 -p 3000" ]
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
    environment:
      - RAILS_ENV=development
    ports:
      - 3001:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: dbpasswd
      POSTGRES_USER: postgres
    ports:
      - 5432:5432